import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { StaffBuilderPrintOptions } from "./staff-builder-print-options";

afterEach(cleanup);
describe("StaffBuilderPrintOptions", () => {
  it("prints the entire piece at four measures per line by default", () => { const print = vi.fn(); render(<StaffBuilderPrintOptions measureCount={4} onCancel={vi.fn()} onPrint={print} />); expect(screen.getByRole("radio", { name: "4" }).getAttribute("checked")).not.toBeNull(); fireEvent.click(screen.getByRole("button", { name: "Print / Save PDF" })); expect(print).toHaveBeenCalledWith({ measureIndexes: [0, 1, 2, 3], measuresPerLine: 4 }); });
  it("offers accessible 2, 3, 4, and 5 options and submits the chosen value with custom ranges", () => { const print = vi.fn(); render(<StaffBuilderPrintOptions measureCount={20} onCancel={vi.fn()} onPrint={print} />); expect(screen.getByRole("group", { name: "Measures per line" })).toBeTruthy(); expect([2, 3, 4, 5].map((value) => screen.getByRole("radio", { name: String(value) }))).toHaveLength(4); fireEvent.click(screen.getByRole("radio", { name: "5" })); fireEvent.click(screen.getByLabelText("Measure ranges", { selector: "input[type=radio]" })); fireEvent.change(screen.getByLabelText("Measure ranges", { selector: "input[type=text]" }), { target: { value: "5-10, 15" } }); fireEvent.click(screen.getByRole("button", { name: "Print / Save PDF" })); expect(print).toHaveBeenCalledWith({ measureIndexes: [4, 5, 6, 7, 8, 9, 14], measuresPerLine: 5 }); });
  it("announces invalid ranges and cancels", () => { const cancel = vi.fn(); render(<StaffBuilderPrintOptions measureCount={4} onCancel={cancel} onPrint={vi.fn()} />); fireEvent.click(screen.getByLabelText("Measure ranges", { selector: "input[type=radio]" })); fireEvent.change(screen.getByLabelText("Measure ranges", { selector: "input[type=text]" }), { target: { value: "4-2" } }); fireEvent.click(screen.getByRole("button", { name: "Print / Save PDF" })); expect(screen.getByRole("alert").textContent).toMatch(/reversed/); fireEvent.click(screen.getByRole("button", { name: "Cancel" })); expect(cancel).toHaveBeenCalledOnce(); });
});
