export const CHORD_ATTEMPT_GRACE_MS = 225;

export const PIANO_NOTE_DURATION_MS = 850;

export const SUCCESS_CHIRP_DELAY_MS = 900;

export const NEXT_TARGET_DELAY_MS = 1250;

export const VIRTUAL_CHORD_REPLAY_DELAY_MS = 900;

export const VIRTUAL_CHORD_SUCCESS_CHIRP_DELAY_MS =
  VIRTUAL_CHORD_REPLAY_DELAY_MS + SUCCESS_CHIRP_DELAY_MS;

export const VIRTUAL_CHORD_NEXT_TARGET_DELAY_MS =
  VIRTUAL_CHORD_SUCCESS_CHIRP_DELAY_MS + 350;
