export const EAR_TRAINING_NOTE_DURATION_MS = 600;
export const EAR_TRAINING_SECOND_NOTE_OFFSET_MS = 700;
export const EAR_TRAINING_FEEDBACK_DELAY_MS = 900;
export const EAR_TRAINING_INCORRECT_SOUND_MS = 250;
